# Generated by Django 5.1.7 on 2025-03-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobtUser',
            new_name='JobUser',
        ),
    ]
