# Generated by Django 5.1.7 on 2025-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joblist_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
